### ISSUE TITLE
[Feature] New chat/message indicator

### ISSUE THREAD

**Issue by ntnguyen1234** [pfgithub/threadclient#1]
I've just discovered this. Great client so far, very fast and light. There's one feature I hope you can integrate into it soon. Right now I can't know if there's a new message or chat that sent to me (replies or chat...). I hope there will be an implementation for it, something simple like this in old.reddit.com

![image](https://user-images.githubusercontent.com/23257168/112924718-9eef7500-914b-11eb-825c-ad35d127c226.png)

**Comment by pfgithub** [comment]
![image](https://user-images.githubusercontent.com/6010774/112932653-21881e00-90d3-11eb-9d1e-9a0ee3ba057c.png)

I've implemented a quick thing that shows you if you have new mail or modmail. Unfortunately, Reddit doesn't expose an API to check for new chat messages so I can't tell when new chat messages are available.

You might have to refresh the page twice for updates to apply.

**Comment by ntnguyen1234** [comment]
Oh I see. Great update.
