### ISSUE TITLE
[Feature Request] allow links to open in same tab

### ISSUE THREAD

**Issue by henkmet** [pfgithub/threadclient#3]
Every click on a link opens in a new tab. It would be great if there is a setting so that the page opens in the same tab. (Maybe this is already possible but I didn't find it?)

**Comment by pfgithub** [comment]
This would be easy to add a setting for. The reason things open in a new tab right now is because otherwise when you go back, it has to reload the page and it doesn't work quite as well.

**Comment by pfgithub** [comment]
Oh, I seem to have broken something in a recent update. There's a new setting, but it's only for external links. Links to other reddit pages shoulld always open in the same tab now.

To upgrade to the latest version of ThreadClient, reload the page and wait for a notice to appear in the bottom right, and then click the "Update (Refresh)" button

^ it's still releasing right now: https://github.com/pfgithub/threadclient/actions/runs/2168708524 so it will be a few minutes before you can do this
