### ISSUE TITLE
[Feature Request] Add a way to get normal reddit link for current subreddit/post

### ISSUE THREAD

**Issue by ShiroYasha139** [pfgithub/threadclient#5]
Sometimes I need to share the original reddit link for a few reasons such as its not viable to use because it doesn't show thumbnails, or lack of video player when used in say, Discord, so I have to manually copy & change the URL before I need to send it.
Other frontends like Libreddit for Reddit, Nitter for Reddit have a button on the top usually besides settings where you can get the original link which you can use, which I think is pretty neat.

**Comment by pfgithub** [comment]
I implemented this and released a new version of threadclient. You can get the update by loading threadclient, waiting a few seconds, and clicking the "Update (refresh)" button in the notification.

![image](https://user-images.githubusercontent.com/6010774/181387400-dccbb711-a5c7-4ebf-801d-d215bee682df.png)

![image](https://user-images.githubusercontent.com/6010774/181387453-8a96d8a4-1d6a-4496-9f3b-b8baae4384f0.png)
