### ISSUE TITLE
[Feature request] Make a (top-level) post

### ISSUE THREAD

**Issue by henkmet** [pfgithub/threadclient#7]
I really like using your viewer to cut out a lot of the reddit clutter. Posting replies is working well but I can't find how to make a new (top-level) post. It would be really nice if that were possible.

**Comment by pfgithub** [comment]
I haven't implemented this yet because of uploading photos. Text posts (without imgaes) and link posts are easy, but uploading images and galleries are a bit complicated because it's only semi documented and some app developers think it might be impossible (it looks possible to me but I haven't tried it yet)

**Comment by pfgithub** [comment]
Implemented and released for text and link posts.

![image](https://user-images.githubusercontent.com/6010774/191774245-cff8ba53-64dc-4e7b-8b86-faa5522d76db.png)

![image](https://user-images.githubusercontent.com/6010774/191802971-a4336590-c1e4-4bc9-87a0-31adabe6675f.png)

- Poll posts are possible but not implemented yet
- Image/video/gallery posts should be possible but are not implemented yet.
- You cannot yet write text posts with embedded media.
- I don't know what talk posts are and they are likely not possible to implement.
- Submitting posts to your user profile is not implemented yet.
- Flairs with editable text cannot be edited yet.
- Creating event posts is not supported yet.
- You cannot yet choose if you want to receive notifications for replies, it defaults on.
- Validation currently only happens after clicking 'post'
- Editing posts is not yet implemented
- Text you enter is not yet saved so navigating away will clear any text

**Comment by henkmet** [comment]
Thank you very much!
