### ISSUE TITLE
[Bug] Sorting by Hot shows r/popular feed even when logged in [Reddit, Localhost]

### ISSUE THREAD

**Issue by ShiroYasha139** [pfgithub/threadclient#8]
Trying out the client locally, its great. However after logging in, the local host page defaults to popular page which doesn't happen on your hosted [website](https://thread.pfg.pw/#reddit).

Localhost
![image](https://user-images.githubusercontent.com/103560009/206403064-c6e65e2d-d591-46dc-834e-63f33fbd99fa.png)

ThreadClient Website
![image](https://user-images.githubusercontent.com/103560009/206403113-421ba08e-8551-4bd4-9566-5500fc0641c3.png)

ThreadClient Website r/popular
![image](https://user-images.githubusercontent.com/103560009/206403136-18c63ce8-1a4f-45b1-aed3-079f3c1b2a4e.png)

Edit:
I was browsing through controversial by hour, then clicked Hot by accident, it seems to be working now somehow.
I don't know what happened.

Another issue:
NSFW thumbnails aren't blurred by default. After clicking "Show" once, they get blurred.

Wasn't sure if I should create another issue, so edited here.

**Comment by pfgithub** [comment]
> local host page defaults to popular page 

Not sure why this would be, it should be sending a request to `reddit.com/.json` which should be popular / home depending on if you're logged in or not. Maybe refreshing the page would solve it? No idea why it was broken or why it fixed itself randomly

> thumbnails aren't blurred by default. After clicking "Show" once, they get blurred

Fixed this, I broke it with the thumbnail change.
